In [4]:
import numpy as np

In [6]:
M = np.array([[1,2,3],[3,4,5],[5,4,3],[0,2,4],[1,3,5]])
print M

[[1 2 3]
 [3 4 5]
 [5 4 3]
 [0 2 4]
 [1 3 5]] [[1 3 5 0 1]
 [2 4 4 2 3]
 [3 5 3 4 5]]


##  (a) Compute M^TM and MM^T

In [11]:
MTM = np.dot(M.T,M)
MMT = np.dot(M,M.T)
print MTM
print 
print MMT

[[36 37 38]
 [37 49 61]
 [38 61 84]]

[[14 26 22 16 22]
 [26 50 46 28 40]
 [22 46 50 20 32]
 [16 28 20 20 26]
 [22 40 32 26 35]]


## (b) and (c) Find eigenvalues and eigenvectors

In [17]:
MTMEigenVals, MTMEigenVecs = np.linalg.eig(MTM)
print "The eigenvalues for MTM are:"
print MTMEigenVals
print
print "The matrix of eigenvector for MTM is:"
print MTMEigenVecs

The eigenvalues for MTM are:
[  1.53566996e+02   1.54330035e+01   2.99519331e-15]

The matrix of eigenvector for MTM is:
[[-0.40928285 -0.81597848  0.40824829]
 [-0.56345932 -0.12588456 -0.81649658]
 [-0.7176358   0.56420935  0.40824829]]


In [18]:
MMTEigenVals, MMTEigenVecs = np.linalg.eig(MMT)
print "The eigenvalues for MMT are:"
print MMTEigenVals
print
print "The matrix of eigenvector for MMT is:"
print MMTEigenVecs

The eigenvalues for MMT are:
[  1.53566996e+02  -2.11358437e-15   1.54330035e+01  -2.52896572e-15
  -2.76412233e-16]

The matrix of eigenvector for MMT is:
[[ 0.29769568  0.94131607 -0.15906393 -0.78507929  0.00659428]
 [ 0.57050856 -0.17481584  0.0332003  -0.08351207 -0.04149694]
 [ 0.52074297 -0.04034212  0.73585663  0.08794197 -0.11286076]
 [ 0.32257847 -0.18826321 -0.5103921  -0.11763897 -0.72117937]
 [ 0.45898491 -0.21515796 -0.41425998  0.59590563  0.68220032]]


the eigenvectors in MTMEigenVecs and MMTEigenVecs are the columns
in these matrices


## (d)  Find the SVD

In [32]:
"""
For MTM, drop the third eigenvalue as it very close to 0.Hence,drop
the third row in MTMEigenVecs.

For MMT, drop the second,fourth and fifth eigenvalue as
it very close to 0. Hence, also drop the corresponding rows in
MMTEigenVecs.
"""
newMTMEigenVals = MTMEigenVals[:-1]
newMTMEigenVecs = numpy.delete(MTMEigenVecs,(2),axis = 0)

newMMTEigenVals = numpy.delete(MMTEigenVals,(1,3,4),axis = 0)
newMMTEigenVecs = numpy.delete(MMTEigenVecs,(1,3,4),axis = 1)
print newMMTEigenVecs

[[ 0.29769568 -0.15906393]
 [ 0.57050856  0.0332003 ]
 [ 0.52074297  0.73585663]
 [ 0.32257847 -0.5103921 ]
 [ 0.45898491 -0.41425998]]


In [36]:
D = np.zeros((5,3))
D[0][0] = np.sqrt(newMTMEigenVals[0])
D[1][1] = np.sqrt(newMTMEigenVals[1])
print D

[[ 12.39221516   0.           0.        ]
 [  0.           3.92848616   0.        ]
 [  0.           0.           0.        ]
 [  0.           0.           0.        ]
 [  0.           0.           0.        ]]


In [45]:
U = newMMTEigenVecs
V = newMTMEigenVecs.T

print U 
print 
print V

[[ 0.29769568 -0.15906393]
 [ 0.57050856  0.0332003 ]
 [ 0.52074297  0.73585663]
 [ 0.32257847 -0.5103921 ]
 [ 0.45898491 -0.41425998]]

[[-0.40928285 -0.56345932]
 [-0.81597848 -0.12588456]
 [ 0.40824829 -0.81649658]]


In [57]:
print U[:,:1]

[[ 0.29769568]
 [ 0.57050856]
 [ 0.52074297]
 [ 0.32257847]
 [ 0.45898491]]


## e) Approximation

In [59]:
"""
For the approximation use choose the biggest eigenvalue,
the first column from V and the first
"""
Approx = np.dot(U[:,:1],np.dot(D[0][0],V[:,:1].T))
print Approx

[[-1.509889   -3.01023347  1.5060724 ]
 [-2.89357443 -5.76885757  2.88626023]
 [-2.64116728 -5.26563883  2.63449111]
 [-1.63609257 -3.26184284  1.63195696]
 [-2.32793529 -4.64115489  2.32205088]]


## f) energy of the original singular value

In [60]:
energy = (D[0][0]**2)/((D[0][0]**2)+(D[1][1]**2))
print energy

0.908680452426
